- hosts: all
  tasks:
    - name: Pull dogpile.cache repo
      git: repo='git://github.com/sqlalchemy/dogpile.cache'
           dest=/opt/stack/dogpile.cache

- hosts: all
  roles:
    - run-devstack
    - role: bindep
      bindep_profile: default

  tasks:
    - name: Ensure nodepool output log directory
      file:
        path: '{{ ansible_user_dir }}/work/logs/nodepool'
        state: directory
