---
- hosts: hypervisor
  remote_user: root
  tasks:
    - name: "Create bundle path"
      file:
        path: "/var/lib/nodepool/oci/{{ container_id }}"
        state: directory

    - name: "Create work directory"
      file:
        path: "/var/lib/zuul/work/{{ container_id }}"
        state: directory
        owner: zuul

    - name: "Write config.json"
      copy:
        src: "{{ container_spec }}"
        dest: "/var/lib/nodepool/oci/{{ container_id }}/config.json"

    - name: "Start container"
      command: >
        runc run --detach --bundle /var/lib/nodepool/oci/{{ container_id }}
            {{ container_id }}

- hosts: localhost
  tasks:
    - name: "Wait for ssh access"
      command: >
        ssh -o StrictHostKeyChecking=no {{ host_addr }} -p {{ container_port }}
            echo okay
      register: access_ok
      failed_when: access_ok.rc not in [0, 255]
      until: access_ok.stdout.find("okay")
