---
- hosts: hypervisor
  remote_user: root
  tasks:
    - name: "Ensure runC is available"
      command: which runc

    - name: "List used port"
      shell: "ss --t -l -n | cut -d: -f2 | awk '/[0-9]/ { print $1 }'"
      register: used_port

    - name: "Ensure / is bind moutned to /mnt"
      shell: 'grep " \/mnt" /proc/mounts || mount -o bind,ro --make-private / /mnt'
      when: use_rootfs

    - name: "List running containers"
      command: runc list -q
      register: running_containers

    - set_fact:
        hypervisor_info:
          ports: "{{ used_port.stdout_lines }}"
          containers: "{{ running_containers.stdout_lines }}"

- hosts: localhost
  tasks:
    - name: "Save results"
      copy:
        content: "{{ hypervisor_info|to_json }}"
        dest: "{{ hypervisor_info_file }}"
        mode: 0400
