- job:
    name: nodepool-functional
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional/run
    post-run: playbooks/nodepool-functional/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/nodepool

- job:
    name: nodepool-functional-src
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-src/run
    post-run: playbooks/nodepool-functional-src/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- project:
    name: openstack-infra/nodepool
    templates:
      - system-required
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
      - publish-openstack-sphinx-docs-infra
      - publish-to-pypi
    check:
      jobs:
        - tox-docs
        - tox-cover
        - tox-pep8
        - tox-py27
        - tox-py35
        - nodepool-functional:
            voting: false
        - nodepool-functional-src:
            voting: false
    post:
      jobs:
        - tox-cover
