- job:
    name: nodepool-functional
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional/run
    post-run: playbooks/nodepool-functional/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/nodepool

- job:
    name: nodepool-functional-src
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-src/run
    post-run: playbooks/nodepool-functional-src/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- job:
    name: nodepool-functional-py35
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35/run
    post-run: playbooks/nodepool-functional-py35/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/nodepool

- job:
    name: nodepool-functional-py35-src
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35-src/run
    post-run: playbooks/nodepool-functional-py35-src/post
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- job:
    name: nodepool-zuul-functional
    parent: legacy-base
    run: playbooks/nodepool-zuul-functional/run
    post-run: playbooks/nodepool-zuul-functional/post
    timeout: 1800
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul

- project:
    name: openstack-infra/nodepool
    templates:
      - system-required
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
      - publish-openstack-sphinx-docs-infra
      - publish-to-pypi
    check:
      jobs:
        - tox-docs
        - tox-cover
        - tox-pep8
        - tox-py27
            branches: ^(?!feature/zuulv3).*$
        - tox-py35
        - nodepool-functional:
            voting: false
            branches: ^(?!feature/zuulv3).*$
        - nodepool-functional-src:
            voting: false
            branches: ^(?!feature/zuulv3).*$
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
    post:
      jobs:
        - tox-cover
    experimental:
      jobs:
        - nodepool-zuul-functional
