- job:
    name: nodepool-zuul-functional
    parent: legacy-base
    run: playbooks/nodepool-zuul-functional/run
    post-run: playbooks/nodepool-zuul-functional/post
    timeout: 1800
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul

- project:
    name: openstack-infra/nodepool
    check:
      jobs:
        - tox-docs
        - tox-cover
        - tox-pep8
        - tox-py35
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
    gate:
        - tox-pep8
        - tox-py35
    experimental:
      jobs:
        - nodepool-zuul-functional
