- hosts: primary
  tasks:
    - name: Copy files from {{ zuul.project.src_dir }}/logs/ on node
      synchronize:
        src: '{{ zuul.project.src_dir}}/logs/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

