- hosts: all

  tasks:
    - include_role:
        name: dib-setup-gate-mirrors

    - debug:
        msg: "{{ devstack_localrc }}"

    - set_fact:
        devstack_localrc: "{{ devstack_localrc | combine( {'DIB_OS_CI_MIRROR_REPOS': dib_gate_mirror_repos } ) }}"

    - debug:
        msg: "{{ devstack_localrc }}"

    - include_role:
        name: run-devstack

    - include_role:
        name: bindep
      vars:
        bindep_profile: default

    - name: Ensure nodepool output log directory
      file:
        path: '{{ ansible_user_dir }}/work/logs/nodepool'
        state: directory
