- hosts: all
  tasks:
    # This role sets up files as required by the openstack-ci-mirrors
    # dib element.  This element configures the image builds to use
    # infra gate mirrors, but is a no-op outside the gate (as is this
    # role).  It creates some repo files and returns the path to the
    # in the dib_gate_mirror_repos fact; below we pass that in
    # devstack local.conf so the nodepool devstack plugin can pass it
    # through to dib via the build options in the config file.
    - include_role:
        name: dib-setup-gate-mirrors

    - include_role:
        name: run-devstack
      vars:
        devstack_localrc_extra:
          DIB_OS_CI_MIRROR_REPOS: "{{ dib_gate_mirror_repos | default(omit) }}"

    - include_role:
        name: bindep
      vars:
        bindep_profile: default

    - name: Ensure nodepool output log directory
      file:
        path: '{{ ansible_user_dir }}/work/logs/nodepool'
        state: directory
