- hosts: all
  roles:
    - dib-setup-gate-mirrors
    - role: run-devstack
      devstack_localrc:
        # NOTE(ianw): this is provided by dib-setup-gate-mirrors, and
        # is a directory with valid repo files that point to the
        # current mirrors
        DIB_OS_CI_MIRROR_REPOS: "{{ dib_gate_mirror_repos|default(omit) }}"
    - role: bindep
      bindep_profile: default

  tasks:
    - name: Ensure nodepool output log directory
      file:
        path: '{{ ansible_user_dir }}/work/logs/nodepool'
        state: directory
