- hosts: all
  roles:
    - run-devstack
    - role: bindep
      bindep_profile: default

  tasks:
    - name: Ensure nodepool output log directory
      file:
        path: '{{ zuul.project.src_dir }}/logs'
        state: directory
