- hosts: all
  tasks:
    - name: Copy nodepool logs from /tmp
      synchronize:
        src: '/tmp/nodepool/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prume-empty-dirs
