- hosts: all
  name: Zuul setup for nodepool test
  tasks:

    - name: Run tools/nodepool-integration-setup.sh from zuul
      shell:
        cmd: tools/nodepool-integration-setup.sh
        chdir: '{{ ansible_user_dir }}/workspace/src/git.openstack.org/openstack-infra/zuul'
      environment: '{{ zuul | zuul_legacy_vars }}'
