- name: Install zookeeper
  package:
    name: zookeeperd
  become: yes

- name: Start zookeeper
  service:
    name: zookeeper
    state: started
  become: yes

- name: Install nodepool
  command: pip3 install .
  args:
    chdir: "{{ zuul.projects['git.openstack.org/openstack-infra/nodepool'].src_dir }}"
  become: yes

- name: Setup logging.conf
  copy:
    content: |
      [loggers]
      keys=root,nodepool,requests,openstack

      [handlers]
      keys=console,normal

      [formatters]
      keys=simple

      [logger_root]
      level=WARNING
      handlers=console

      [logger_requests]
      level=WARNING
      handlers=normal
      qualname=requests

      [logger_openstack]
      level=WARNING
      handlers=normal
      qualname=openstack

      [logger_gear]
      level=DEBUG
      handlers=normal
      qualname=gear

      [logger_nodepool]
      level=DEBUG
      handlers=normal
      qualname=nodepool

      [handler_console]
      level=WARNING
      class=StreamHandler
      formatter=simple
      args=(sys.stdout,)

      [handler_normal]
      level=DEBUG
      class=FileHandler
      formatter=simple
      args=('{{ ansible_user_dir }}/work/logs/nodepool/launcher.log',)

      [formatter_simple]
      format=%(asctime)s %(levelname)s %(name)s: %(message)s
      datefmt=
    dest: "{{ ansible_user_dir }}/work/etc/logging.conf"

- name: Setup nodepool.yaml
  copy:
    content: |
      zookeeper-servers:
        - host: localhost
      images-dir: "{{ ansible_user_dir }}/work/images/"
      build-log-dir: "{{ ansible_user_dir }}/work/logs/nodepool/"
    dest: "{{ ansible_user_dir }}/work/etc/nodepool.yaml"

- name: Setup secure.conf
  copy:
    content: ""
    dest: "{{ ansible_user_dir }}/work/etc/secure.conf"

- name: Start the service
  command: nodepool-launcher -c etc/nodepool.yaml -s etc/secure.conf -l etc/logging.conf -p launcher.pid
  args:
    chdir: "{{ ansible_user_dir }}/work/"
