- hosts: launcher
  roles:
    - role: bindep
      bindep_profile: dev

  tasks:
    - name: Ensure nodepool services directories
      file:
        path: '{{ ansible_user_dir }}/{{ item }}'
        state: directory
      with_items:
        - work/logs/nodepool
        - work/etc
        - work/images
        - .kube

- hosts: cluster
  roles:
    - install-openshift
