- hosts: all
  roles:
    - collect-container-logs
  tasks:
    - name: Copy nodepool logs
      ignore_errors: yes
      block:
        - name: Write out openstack logs
          become: true
          shell:
          cmd: |
            u=""
            name=""
            for u in $(systemctl list-unit-files | grep devstack | awk '{print $1}'); do
              name=$(echo $u | sed 's/devstack@/screen-/' | sed 's/\.service//')
              journalctl -o short-precise --unit $u  > /var/log/nodepool/$name.txt
            done
        - name: Copy nodepool log files
          synchronize:
            src: /var/log/nodepool
            dest: '{{ zuul.executor.log_root }}'
            mode: pull
        - name: Copy nodepool config files
          synchronize:
            src: /etc/nodepool
            dest: '{{ zuul.executor.log_root }}'
            mode: pull
        - name: Copy instance console logs
          become: true
          synchronize:
            src: /opt/stack/data/nova/instances
            dest: '{{ zuul.executor.log_root }}'
            mode: pull
            rsync_opts:
              - "--include=*/"
              - "--include=console.log"
              - "--exclude=*"
        - name: Copy syslog
          become: True
          synchronize:
            src: "/var/log/syslog"
            dest: '{{ zuul.executor.log_root }}'
            mode: pull

        - name: Copy docker logs
          become: True
          synchronize:
            src: '{{ ansible_user_dir }}/zuul-output/logs/docker'
            dest: '{{ zuul.executor.log_root }}'
            mode: pull
