- hosts: all
  roles:
    - stage-output
    - collect-container-logs
  tasks:
    - name: Copy nodepool logs
      ignore_errors: yes
      block:
        - name: Copy instance console logs
          become: true
          synchronize:
            src: /opt/stack/data/nova/instances
            dest: '{{ zuul.executor.log_root }}'
            mode: pull
            rsync_opts:
              - "--include=*/"
              - "--include=console.log"
              - "--exclude=*"
