- hosts: all
  roles:
    # for zookeeper, etc. on host
    - role: bindep
      bindep_dir: "{{ zuul.projects['opendev.org/zuul/nodepool'].src_dir }}"
    - role: test-setup
      zuul_work_dir: "{{ zuul.projects['opendev.org/zuul/nodepool'].src_dir }}"
    - role: ensure-zookeeper
      zookeeper_use_tls: true
    - role: ensure-docker
      vars:
        _docker_upstream_distro_packages:
          - docker-ce=5:20.10.5~3-0~ubuntu-focal
          - docker-ce-cli=5:20.10.5~3-0~ubuntu-focal
          - containerd.io
    # Note: keep after ensure-docker
    - use-buildset-registry
    - ensure-devstack
  tasks:
    - name: Install docker-compose dependencies
      package:
        name:
          - docker-compose
      become: yes
    - name: Create a local user that matches the container UID
      user:
        name: nodepool
        comment: nodepool
        uid: 10001
      become: yes

