- hosts: all
  roles:
    # for zookeeper, etc. on host
    - role: bindep
      bindep_dir: "{{ zuul.projects['opendev.org/zuul/nodepool'].src_dir }}"
    - role: test-setup
      zuul_work_dir: "{{ zuul.projects['opendev.org/zuul/nodepool'].src_dir }}"
    - role: ensure-zookeeper
      zookeeper_use_tls: true
    - ensure-docker
    # Note: keep after ensure-docker
    - use-buildset-registry
    - role: ensure-devstack
      vars:
        ensure_devstack_git_refspec: 'refs/changes/changes/71/793271/1'
        ensure_devstack_git_version: 'FETCH_HEAD'
  tasks:
    - name: Install docker-compose dependencies
      package:
        name:
          - docker-compose
      become: yes
    - name: Create a local user that matches the container UID
      user:
        name: nodepool
        comment: nodepool
        uid: 10001
      become: yes

