- hosts: all
  vars:
    docker_log: '{{ ansible_user_dir }}/zuul-output/logs/docker.txt'
    minikube_log: '{{ ansible_user_dir }}/zuul-output/logs/minikube.txt'

  tasks:
    - name: Produce minikube log
      become: yes
      shell: '/tmp/minikube logs > {{ minikube_log }}'
      environment:
        MINIKUBE_HOME: "{{ ansible_user_dir }}"

    - name: Get docker system logs
      become: yes
      shell: 'journalctl -u docker > {{ docker_log }}'
