- hosts: all
  tasks:
    - name: Copy nodepool log files
      synchronize:
        src: /var/log/nodepool
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
    - name: Copy nodepool config files
      synchronize:
        src: /etc/nodepool
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
