version: "3"

services:
  zookeeper:
    container_name: nodepool-test-zookeeper
    user: "${USER_ID}"
    image: zookeeper
    ports:
      - "2281:2281"
    tmpfs:
      - /data:uid=${USER_ID}
      - /datalog:uid=${USER_ID}
    volumes:
      - "./ca:/var/certs:z"
      - "./zoo.cfg:/conf/zoo.cfg:z"
