version: "3"

services:
  zookeeper:
    container_name: nodepool-test-zookeeper
    image: zookeeper
    tmpfs:
      - /data
      - /datalog
    volumes:
      - "./ca:/var/certs:z"
      - "./zoo.cfg:/conf/zoo.cfg:z"
    network_mode: host
  nodepool-testing-container:
    container_name: nodepool-testing-container
    image: nodepool-testing-container
    volumes:
      - "../:/nodepool:z"
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      - zookeeper